version: '3.8'
services:
  mamz-web-app:
    image: maclass23/mamz-fierce:3
    ports:
      - 8080:8080
  postgres:
    image: postgres:13
    ports:
      - 5432:5432
    environment: 
    POSTGRES_PASSWORD=my-pwd 